# Generated by Django 2.1.3 on 2019-01-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebdavServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Name')),
                ('url', models.CharField(default='', max_length=100, verbose_name='Server URL')),
                ('path', models.CharField(default='', max_length=100, verbose_name='Ordner Pfad')),
                ('username', models.CharField(default='', max_length=100, verbose_name='Benutzer Name')),
                ('password', models.CharField(default='', max_length=100, verbose_name='Passwort')),
                ('menu_title', models.CharField(default='', max_length=100, verbose_name='Menu Titel')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('type', models.PositiveIntegerField(choices=[(1, 'User'), (2, 'Admin')], verbose_name='Typ')),
            ],
        ),
    ]
