# Generated by Django 2.2.6 on 2019-11-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico_webdav', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webdavserver',
            name='sortby',
            field=models.PositiveIntegerField(choices=[(1, 'Dateiname aufsteigend'), (2, 'Dateiname absteigend'), (3, 'Änderungsdatum aufsteigend'), (4, 'Änderungsdatum absteigend')], default=1, verbose_name='Sortieren nach'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='webdavserver',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Benutzer'), (2, 'Admin')], verbose_name='Typ'),
        ),
        migrations.AlterField(
            model_name='webdavserver',
            name='username',
            field=models.CharField(default='', max_length=100, verbose_name='Benutzername'),
        ),
    ]
