# Generated by Django 5.2.14 on 2026-06-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico_webdav', '0002_auto_20191111_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='webdavserver',
            name='menu_title_de',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Menu Titel'),
        ),
        migrations.AddField(
            model_name='webdavserver',
            name='menu_title_fr',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Menu Titel'),
        ),
    ]
